### ISSUE TITLE
errors while working as root

### ISSUE THREAD

**Issue by e-g-hategan** [dr4Ke/git-preserve-permissions#3]
This seems to be a really nice tool. Many thanks however I have an issue with it. 

I'm working as root in order to be able to read all the files. 
I've staged .git-preserve-permissions but it would still not commit it. Please note I've done `git-preserve-permissions --save` twice so that permissions for `.git-preserve-permissions` are included - that makes sense. 
Also I've tried with autosave both on and off to no avail.

```
# git commit -a -m "Initial version"
Some file(s) metadata has changed
Use git-preserve-permissions --check --verbose for more information
Execute 'git preserve-permissions --save' to save new permissions
Execute 'git preserve-permissions --restore' to restore old permissions
# git-preserve-permissions --check --verbose
Checking...
Some file(s) metadata has changed
.git-preserve-permissions: user changed from -1 to 0, group changed from -1 to 0,
```

Here's my relevant config
```
# git config --list
preserve-permissions.user=true
preserve-permissions.group=true
preserve-permissions.perms=0777
preserve-permissions.autosave=false
```

When working as non root I managed to commit but was missing some files that it couldn't read.

**Comment by dr4Ke** [comment]
This tool is really meant to be used as root, so there shouldn't have a problem with that.
This may be related to a configuration change between the `git-preserve-permissions --save` and the commit time. What do you have in the `.git-preserve-permissions` for this very file and for some others? Is there user/group information in the file already?
I don't use this tool currently, and I didn't manage to merge the `new_develop` branch in `master` three years ago. But there was a change in this branch to address the "configuration change" issue. If that's your issue, you could try with this branch. In the meantime, I'll try to finalize my work on it and release it.

**Comment by e-g-hategan** [comment]
Thank you for the fast response. 

In `.git-preserve-permissions` I have the following (file / folder names obfuscated): 
```
# git diff --staged .git-preserve-permissions 
diff --git a/.git-preserve-permissions b/.git-preserve-permissions
new file mode 100644
index 0000000..e9502ac
--- /dev/null
+++ b/.git-preserve-permissions
@@ -0,0 +1,5 @@
+0644:0:0:.git-preserve-permissions
+0664:1000:1000:folder1/file1
+0664:1000:1000:folder1/file2
+0664:1000:1000:file3
+0664:1000:1000:folder2/file4
```
and
```
# ls -l
-rw-rw-r-- 1 eh   eh   76621890 Jan 11 19:39 folder1/file1
-rw-rw-r-- 1 eh   eh        487 Jan 11 19:39 folder1/file2
-rw-rw-r-- 1 eh   eh        505 Jan  7 21:54 file3
-rw-r--r-- 1 root root      176 Jan 12 18:36 .git-preserve-permissions
-rw-rw-r-- 1 eh   eh       1359 Jan 11 19:39 folder2/file4
```
Yes, file1 is 76M

**Comment by dr4Ke** [comment]
It's strange. The file contains what it should. I just tested it and could reproduce the issue.
Anyway, I updated my repository yesterday with a 1.3 version. It should work with this release. Can you try it?

**Comment by e-g-hategan** [comment]
Thanks, will give it a try

**Comment by e-g-hategan** [comment]
Indeed it all works fine. Thank you for the very quick turnaround.

**Comment by dr4Ke** [comment]
OK. I'll close the issue, then.
